# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ictus', '0020_auto_20161201_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intraarterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('tici', models.CharField(blank=True, null=True, max_length=2, choices=[('0', 'No perfusión'), ('1', 'Penetración con mínima perfusión'), ('2', 'Perfusión parcial'), ('2A', 'Relleno parcial'), ('2B', 'Relleno completo'), ('3', 'Perfusión completa')], verbose_name='TICI')),
                ('iniciomicro', models.FloatField(blank=True, null=True, verbose_name='Tiempo inicio micro')),
            ],
            options={
                'verbose_name_plural': 'Extracciones',
            },
        ),
        migrations.RemoveField(
            model_name='extraccion',
            name='episodio',
        ),
        migrations.RenameField(
            model_name='basal',
            old_name='antiagregacion_previa',
            new_name='antiagregante',
        ),
        migrations.RenameField(
            model_name='basal',
            old_name='anticoagulacion_previa',
            new_name='anticoagulante',
        ),
        migrations.RenameField(
            model_name='basal',
            old_name='dislipemia',
            new_name='dl',
        ),
        migrations.RenameField(
            model_name='basal',
            old_name='diabetes',
            new_name='dm',
        ),
        migrations.RenameField(
            model_name='basal',
            old_name='estatina_previas',
            new_name='estatinas',
        ),
        migrations.RenameField(
            model_name='basal',
            old_name='HTA',
            new_name='hta',
        ),
        migrations.RenameField(
            model_name='basal',
            old_name='rankin',
            new_name='rankinbasal',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='duplex_dtc_ipsilateral',
            new_name='duplex_dtcipsilateral',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='duplex_dtc_otro',
            new_name='duplex_dtcotro',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='ecocardio_cardioembolico',
            new_name='ecocardiocardioembolico',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='ecocardio_fecha',
            new_name='ecocardiofecha',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='ecocardio_hallazgos',
            new_name='ecocardiohallazgos',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='ecocardio_hecho',
            new_name='ecocardiohecho',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='ecodilatacion_ai',
            new_name='ecodilatacionai',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='ecosta_50_ipsi',
            new_name='ecosta50ipsi',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='ecotsa_contra',
            new_name='ecotsacontra',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='ecotsa_ipsi',
            new_name='ecotsaipsi',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='holter_fecha',
            new_name='holterfecha',
        ),
        migrations.RenameField(
            model_name='intervencion',
            old_name='holter_hallazgos',
            new_name='holterhallazgos',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_nacimiento',
            new_name='fechanacim',
        ),
        migrations.RenameField(
            model_name='seguimiento',
            old_name='causa_muerte',
            new_name='causamuerte',
        ),
        migrations.RenameField(
            model_name='seguimiento',
            old_name='fecha_muerte',
            new_name='fechamuerte',
        ),
        migrations.RenameField(
            model_name='seguimiento',
            old_name='nihss_3meses',
            new_name='nihss3m',
        ),
        migrations.RenameField(
            model_name='seguimiento',
            old_name='rankin_3meses',
            new_name='rankin3m',
        ),
        migrations.RenameField(
            model_name='seguimiento',
            old_name='toast_3meses',
            new_name='toast3m',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='ACFA_previa',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='HTA_tiempo',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='IAM',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='SAOS',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='TVP',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='antecedentes_familiares',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='arritmia_previa',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='cancer_tipo',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='cardiopatia_isquemica',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='deterioro_cognitivo',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='migrana',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='otras_cardiopatias',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='otras_patologias',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='tabaco_paquetes_acumulados',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='tiempo_diabetes',
        ),
        migrations.RemoveField(
            model_name='basal',
            name='tipo_diabetes',
        ),
        migrations.RemoveField(
            model_name='episodio',
            name='hemo_etiologia',
        ),
        migrations.RemoveField(
            model_name='episodio',
            name='hemo_localizacion',
        ),
        migrations.RemoveField(
            model_name='episodio',
            name='oclusion',
        ),
        migrations.RemoveField(
            model_name='episodio',
            name='oclusion_lugar',
        ),
        migrations.RemoveField(
            model_name='episodio',
            name='tibidtc',
        ),
        migrations.RemoveField(
            model_name='episodio',
            name='tipo_ictus',
        ),
        migrations.RemoveField(
            model_name='intervencion',
            name='anticoag_nombre',
        ),
        migrations.RemoveField(
            model_name='intervencion',
            name='iniciomicro',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='basal',
            name='anticoagnombre',
            field=models.CharField(blank=True, null=True, max_length=300),
        ),
        migrations.AddField(
            model_name='basal',
            name='cancerdxposterior',
            field=models.IntegerField(blank=True, null=True, choices=[('00', 'No'), ('01', 'Sí'), ('02', 'Indeterminado')], verbose_name='Cancer diagnosticado tras el ictus'),
        ),
        migrations.AddField(
            model_name='basal',
            name='cardiopatia',
            field=models.CharField(blank=True, null=True, max_length=2, choices=[('00', 'No'), ('01', 'Sí'), ('02', 'Indeterminado')], verbose_name='Cardiopatía'),
        ),
        migrations.AddField(
            model_name='basal',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='basal',
            name='tipo_cardiopatia',
            field=models.IntegerField(blank=True, null=True, choices=[(0, 'Cardiopatía isquémica'), (1, 'Cardiopatía valvular'), (2, 'Otras'), (3, 'Mixta')], verbose_name='Tipo de cardiopatía'),
        ),
        migrations.AddField(
            model_name='episodio',
            name='idtrombo',
            field=models.CharField(max_length=16, verbose_name='ID2', default='TR000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episodio',
            name='mimic',
            field=models.CharField(blank=True, null=True, max_length=2, choices=[('00', 'No'), ('01', 'Sí'), ('02', 'Indeterminado')], verbose_name='AIT o Ictus Mimic'),
        ),
        migrations.AddField(
            model_name='episodio',
            name='toastindet',
            field=models.IntegerField(blank=True, null=True, choices=[(0, 'Criptogenico'), (1, 'Incompleto'), (2, 'Coexistencia')], verbose_name='TOAST Indeterminado'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='recurrencia',
            field=models.IntegerField(blank=True, null=True, choices=[('00', 'No'), ('01', 'Sí')], verbose_name='Recurrencia'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='recurrenciafecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la recurrencia'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='recurrenciatoast',
            field=models.CharField(blank=True, null=True, max_length=2, choices=[('1', 'Aterotrombótico'), ('2', 'Cardioembólico'), ('3', 'Lacunar'), ('4', 'De otra etiología determinada/causa infrecuente'), ('5', 'Indeterminado, >2 causas'), ('6', 'Indeterminado, tras estudio completo'), ('7', 'Indeterminado, estudio incompleto')], verbose_name='TOAST recurrencia'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='recurrenciavasc',
            field=models.IntegerField(blank=True, null=True, choices=[('00', 'No'), ('01', 'Sí')], verbose_name='Recurrencia vascular'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='recurrenciavascfecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la recurrencia vascular'),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, max_length=16, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Extraccion',
        ),
        migrations.AddField(
            model_name='intraarterial',
            name='episodio',
            field=models.ForeignKey(null=True, to='ictus.Episodio'),
        ),
    ]
